server:
  port: 8081

spring:
  datasource:
#    url: jdbc:mysql://i4C102.p.ssafy.io:3306/hunsu?serverTimezone=Asia/Seoul
#    username: ssafyC102
#    password: durtlrhdbckd135
    url: jdbc:mysql://localhost:3306/hunsu2?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    open-in-view: false

  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: wogml23@$0@

  url:
    base: http://localhost:8081

  social:
    kakao:
      client_id: 16ae1e2e85a16538664e419b8e1a468f
      client_secret: g5Gqw9mULSYEzLQBBmK8PW1pbSRBBvBE
      redirect: /v1/auth/usercheck
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me

logging:
  level:
    root: info