spring:
  datasource:
    url: jdbc:mysql://i4C102.p.ssafy.io:3306/hunsu?serverTimezone=Asia/Seoul
    username: ssafyC102
    password: durtlrhdbckd135
    driver-class-name: com.mysql.cj.jdbc.Driver



  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true

oauth2:
  kakao:
    client-id: 6ab2b1fa25ea8dc7edf27eb1c42fcd4c
    client-secret: 7leAsgMurNqMLpi0cABJ7AhdP0oIqqPb